/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/dd.glb -o src/components/WomenTwo.jsx 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Womens(props) {
  const { nodes, materials } = useGLTF("models/dd.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={
          nodes["tripo_node_71ead19e-56e3-4ec8-bd8d-dab351c2e05d"].geometry
        }
        material={materials["tripo_mat_71ead19e-56e3-4ec8-bd8d-dab351c2e05d"]}
      />
    </group>
  );
}

useGLTF.preload("models/dd.glb");
