/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 dance.glb -o dance.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/dance.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['tripo_node_5d5eb79c-33bc-4812-af92-831f94f522bc'].geometry} material={materials['tripo_mat_5d5eb79c-33bc-4812-af92-831f94f522bc']} />
    </group>
  )
}

useGLTF.preload('/dance.glb')
